mysql:
    host: localhost
    user: 
    passwd: 
    db: 

mysql_heroku:
    host: us-cdbr-iron-east-03.cleardb.net
    user: bbaf414965fded
    passwd: 2f3310e8
    db: heroku_fa3c47157b8ffc1

scanalytics:
    username: 
    password: 
    clientId: 
    clientSecret: 
    array_key_list: 

other:
    preprocessing_queue:
        - preprocessing.scale_and_center
        - preprocessing.dot_reduction
        - preprocessing.connect_lines
    use_anonymous: yes
