mysql:
    host: localhost
    user: cs349common
    passwd: gogocs349
    db: cs349

mysql_heroku:
    host: us-cdbr-iron-east-03.cleardb.net
    user: bbaf414965fded
    passwd: 2f3310e8
    db: heroku_fa3c47157b8ffc1

scanalytics:
    username: tran_h3@denison.edu
    password: makeitcount
    clientId: 41082c49d21ec03ab278adadca407567585621e5
    clientSecret: e74845de757512ca7d9ca78a809a8d9335ad5d7cebc385c192f71e47d0be9d7a
    array_key_list: 1AMDJ

other:
    preprocessing_queue:
        - preprocessing.scale_and_center
        - preprocessing.dot_reduction
        - preprocessing.connect_lines
    use_anonymous: yes